/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 755be59268aa34a8bdbdfe547f6e8889)
interface __BaseEnv_Env {
	GAME_ROOM: DurableObjectNamespace<import("./worker/index").GameRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "GameRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
