/**
 * Seabed multi-material tests (node, no GPU):
 * - catalogue: 22 layers, every one used by some region, big-feature sets (rot
 *   "always") only in B slots, main ≠ alt, every region's look distinct;
 * - catalogue keys match the asset pipeline (scripts/deep-march-materials.py) and
 *   every shipped file exists with the expected KTX2 encoding / size / mip chain;
 * - materialFiles.ts (generated byte sizes) matches the shipped files;
 * - MaterialDownload: every layer fetched before the dive, byte / layer progress,
 *   retries per file, switch to the WebP path, final failure + user retry.
 */
import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { B_SLOTS, LAYERS, LAYER_COUNT, PALETTE_COUNT, REGION_PALETTES, layersOfRegion, paletteOf, regionsOfLayer } from "../src/games/deep-march/scene/materialCatalog";
import { MATERIAL_RETRIES, MaterialDownload, layerFiles, pathBytes } from "../src/games/deep-march/scene/materialDownload";
import { MATERIAL_FILE_BYTES } from "../src/games/deep-march/scene/materialFiles";
import { MAT_DECLS } from "../src/games/deep-march/scene/materialShader";
import { REGION_COUNT } from "../src/games/deep-march/terrain/regions";

let fails = 0;
const check = (ok: boolean, msg: string) => {
  if (!ok) {
    fails++;
    console.error("FAIL", msg);
  }
};

// ---- catalogue
check(LAYER_COUNT === 22, `22 layers (got ${LAYER_COUNT})`);
check(REGION_PALETTES.length === REGION_COUNT && PALETTE_COUNT === 2 * REGION_COUNT, "one main+alt palette per region");
check(new Set(LAYERS.map((l) => l.key)).size === LAYER_COUNT, "unique keys");
for (let i = 0; i < LAYER_COUNT; i++) check(regionsOfLayer(i).length > 0, `layer ${LAYERS[i].key} used by a region`);
for (let p = 0; p < PALETTE_COUNT; p++) {
  const pal = paletteOf(p);
  check(pal.length === 5 && pal.every((l) => l >= 0 && l < LAYER_COUNT), `palette ${p} valid`);
  pal.forEach((l, s) => {
    if (LAYERS[l].rot === "always") check((B_SLOTS as readonly number[]).includes(s), `big-feature ${LAYERS[l].key} only in B slots (palette ${p} slot ${s})`);
  });
  check(pal[0] !== pal[1], `palette ${p}: floor A ≠ floor B`);
}
for (const key of ["basalt", "coralcrust", "lichen"]) check(LAYERS.find((l) => l.key === key)?.rot === "always", `${key} uses the rotated second scale`);
for (let r = 0; r < REGION_COUNT; r++) {
  const { main, alt, altAt } = REGION_PALETTES[r];
  check(main.join() !== alt.join(), `region ${r}: alt differs from main`);
  check(altAt > 0.3 && altAt < 0.8, `region ${r}: alt patches cover part of the region`);
  for (let q = 0; q < r; q++) {
    const a = REGION_PALETTES[q].main;
    const same = main.filter((l, s) => a[s] === l).length;
    check(same <= 3, `regions ${q} and ${r} main palettes distinct (${same}/5 slots equal)`);
    check(new Set(layersOfRegion(r)).size !== new Set(layersOfRegion(q)).size || layersOfRegion(r).some((l) => !layersOfRegion(q).includes(l)), `regions ${q}/${r} layer sets differ`);
  }
}
// the shader's merged entry list holds every (layer, floor/side) pair two blending regions can need
{
  const cap = Number(/#define DM_ENTRIES (\d+)/.exec(MAT_DECLS)?.[1]);
  let worst = 0;
  for (let a = 0; a < REGION_COUNT; a++) for (let b = 0; b < REGION_COUNT; b++) {
    const e = new Set<string>();
    for (const r of [a, b]) for (const pal of [REGION_PALETTES[r].main, REGION_PALETTES[r].alt]) pal.forEach((l, s) => e.add(`${l}:${s < 2}`));
    worst = Math.max(worst, e.size);
  }
  check(worst <= cap, `shader entry list (${cap}) fits the worst region pair (${worst})`);
}
// terrace keeps the original 4-set look as its main palette
const T = REGION_PALETTES[4].main.map((l) => LAYERS[l].key);
check(T.join() === "sand,gravel,rock,moss,rock", `terrace main = original look (${T})`);

// ---- pipeline / assets
const py = readFileSync("scripts/deep-march-materials.py", "utf8");
const pyKeys = [...py.slice(py.indexOf("SETS = ["), py.indexOf("]", py.indexOf("SETS = ["))).matchAll(/\("(\w+)", "(acg|ph)"/g)].map((m) => m[1]);
check(pyKeys.join() === LAYERS.map((l) => l.key).join(), `pipeline SETS order = catalogue (${pyKeys.join()})`);
const credits = readFileSync("src/games/deep-march/assets/CREDITS.md", "utf8");
const dir = "src/games/deep-march/assets/materials";
const ktx = (f: string) => {
  const b = readFileSync(`${dir}/${f}`);
  const v = new DataView(b.buffer, b.byteOffset, b.byteLength);
  const id = [0xab, 0x4b, 0x54, 0x58, 0x20, 0x32, 0x30, 0xbb, 0x0d, 0x0a, 0x1a, 0x0a];
  check(id.every((x, k) => b[k] === x), `${f}: KTX2 identifier`);
  return { vk: v.getUint32(12, true), w: v.getUint32(20, true), h: v.getUint32(24, true), levels: v.getUint32(40, true), scheme: v.getUint32(44, true) };
};
for (const l of LAYERS) {
  check(credits.includes(`\`${l.key}\``), `CREDITS lists ${l.key}`);
  for (const f of ["a1024.ktx2", "a512.ktx2", "n512.ktx2", "a512.webp", "n512.webp"]) check(existsSync(`${dir}/${l.key}_${f}`), `${l.key}_${f} exists`);
  for (const [f, size, scheme] of [["a1024", 1024, 1], ["a512", 512, 1], ["n512", 512, 2]] as const) {
    if (!existsSync(`${dir}/${l.key}_${f}.ktx2`)) continue;
    const h = ktx(`${l.key}_${f}.ktx2`);
    check(h.vk === 0 && h.w === size && h.h === size, `${l.key}_${f}: ${size}² Basis (vk ${h.vk}, ${h.w}×${h.h})`);
    check(h.levels === Math.log2(size) + 1, `${l.key}_${f}: full mip chain (${h.levels})`);
    check(h.scheme === scheme, `${l.key}_${f}: ${scheme === 1 ? "ETC1S/BasisLZ" : "UASTC+zstd"} (scheme ${h.scheme})`);
  }
}

// ---- generated sizes
{
  const shipped = readdirSync(dir).filter((f) => /\.(ktx2|webp)$/.test(f)).sort();
  check(shipped.join() === Object.keys(MATERIAL_FILE_BYTES).sort().join(), `materialFiles.ts lists exactly the shipped files (${shipped.length})`);
  for (const f of shipped) check(MATERIAL_FILE_BYTES[f] === statSync(`${dir}/${f}`).size, `${f}: size in materialFiles.ts`);
  check(existsSync("src/games/deep-march/scene/materialStream.ts") === false, "no runtime streaming module left");
  const shader = readFileSync("src/games/deep-march/scene/materialShader.ts", "utf8");
  check(!/uLayerS|stand-in|dmFetch/.test(shader.replace(/no stand-ins/, "")), "shader has no stand-in / cross-fade path");
}

// ---- MaterialDownload
{
  const mb = (b: number) => (b / 1e6).toFixed(2);
  for (const low of [false, true]) {
    const d = new MaterialDownload(low);
    const total = pathBytes("ktx2", low);
    let snap = d.snapshot();
    check(snap.done === 0 && snap.total === LAYER_COUNT && snap.bytes === 0 && snap.totalBytes === total && snap.last === -1, `${low ? "phone" : "desktop"}: empty start, total ${mb(total)} MB`);
    check(layerFiles(4, "ktx2", low)[0] === `basalt_a${low ? 512 : 1024}.ktx2` && layerFiles(4, "ktx2", low)[1] === "basalt_n512.ktx2", "ktx2 files per platform");
    // catalogue order, one at a time
    const order: number[] = [];
    for (let k = 0; k < 4; k++) order.push(d.next());
    check(order.join() === "0,1,2,3" && d.state.slice(0, 4).every((s) => s === "loading"), "layers handed out in order, marked loading");
    // byte progress (partial), clamped to the file size
    const [fa, fn] = d.files(0);
    d.progress(fa, 1000);
    d.progress(fn, 1e12);
    snap = d.snapshot();
    check(snap.bytes === 1000 + MATERIAL_FILE_BYTES[fn], `partial bytes counted and clamped (${snap.bytes})`);
    // a failed attempt restarts that file's bytes; retries are bounded
    const retries: boolean[] = [];
    for (let k = 0; k <= MATERIAL_RETRIES; k++) retries.push(d.attemptFailed(fa));
    check(retries.slice(0, MATERIAL_RETRIES).every(Boolean) && !retries[MATERIAL_RETRIES], `${MATERIAL_RETRIES} retries per file, then give up`);
    check(d.snapshot().bytes === MATERIAL_FILE_BYTES[fn], "failed attempt's bytes reset");
    check(d.attemptsOf(fa) === MATERIAL_RETRIES + 1, "attempt count");
    // KTX2 abandoned → every layer again from WebP, totals switch
    d.layerDone(1);
    d.switchToWebp();
    snap = d.snapshot();
    check(snap.path === "webp" && snap.fellBack && snap.done === 0 && snap.bytes === 0 && snap.totalBytes === pathBytes("webp", low) && d.state.every((s) => s === "idle"), "switch to WebP resets everything");
    check(d.files(0)[0] === "sand_a512.webp", "webp files");
    // complete all but one; the last fails for good, user retry brings it back
    let i: number;
    const got: number[] = [];
    while ((i = d.next()) >= 0) got.push(i);
    check(got.length === LAYER_COUNT, "every layer requested (no lazy layers)");
    for (const l of got.slice(0, -1)) {
      for (const f of d.files(l)) d.progress(f, MATERIAL_FILE_BYTES[f]);
      d.layerDone(l);
    }
    const lastL = got[got.length - 1];
    d.layerFailed(lastL);
    snap = d.snapshot();
    check(!d.allDone() && snap.failed === 1 && snap.done === LAYER_COUNT - 1 && snap.last === got[got.length - 2], "final failure blocks completion");
    d.retryFailed();
    check(d.state[lastL] === "idle" && d.next() === lastL, "retry re-requests the failed layer");
    d.layerDone(lastL);
    snap = d.snapshot();
    check(d.allDone() && snap.bytes === snap.totalBytes && snap.done === LAYER_COUNT && snap.failed === 0, "all done: bytes = total");
  }
  console.log(`  download totals: desktop ktx2 ${mb(pathBytes("ktx2", false))} MB · phone ktx2 ${mb(pathBytes("ktx2", true))} MB · webp fallback ${mb(pathBytes("webp", false))} MB`);
}

if (fails) {
  console.error(`${fails} material test(s) failed`);
  process.exit(1);
}
console.log("materials ok");
