/**
 * Seabed multi-material tests (node, no GPU):
 * - catalogue: 22 layers, every one used by some region, big-feature sets (rot
 *   "always") only in B slots, main ≠ alt, every region's look distinct; the ring
 *   wall's 「界壁」 palettes as material slot 6;
 * - catalogue keys match the asset pipeline (scripts/deep-march-materials.py) and
 *   every shipped file exists with the expected KTX2 encoding / size / mip chain;
 * - layer selection (materialSelect.ts, SELECT in materialShader.ts): top-2 per
 *   surface group is exact with <= 2 distinct layers, keeps the group weight and
 *   has no jumps (rank swaps, one-palette shortcut borders);
 * - materialFiles.ts (generated byte sizes) matches the shipped files;
 * - MaterialDownload: every layer fetched before the dive, byte / layer progress,
 *   retries per file, switch to the WebP path, final failure + user retry.
 */
import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { B_SLOTS, LAYERS, LAYER_COUNT, PALETTE_COUNT, REGION_PALETTES, WALL_MATERIAL, WALL_PALETTES, layersOfRegion, paletteOf, regionsOfLayer } from "../src/games/deep-march/scene/materialCatalog";
import { MATERIAL_RETRIES, MaterialDownload, layerFiles, pathBytes } from "../src/games/deep-march/scene/materialDownload";
import { MATERIAL_FILE_BYTES } from "../src/games/deep-march/scene/materialFiles";
import { selectLayersJS } from "../src/games/deep-march/scene/materialShader";
import { topTwoJS } from "../src/games/deep-march/scene/materialSelect";
import { REGION_COUNT } from "../src/games/deep-march/terrain/regions";

let fails = 0;
const check = (ok: boolean, msg: string) => {
  if (!ok) {
    fails++;
    console.error("FAIL", msg);
  }
};

// ---- catalogue
check(LAYER_COUNT === 22, `22 layers (got ${LAYER_COUNT})`);
check(REGION_PALETTES.length === REGION_COUNT && PALETTE_COUNT === 2 * (REGION_COUNT + 1), "one main+alt palette per region, + the ring wall's");
check(WALL_MATERIAL === REGION_COUNT && paletteOf(2 * WALL_MATERIAL) === WALL_PALETTES.main && paletteOf(2 * WALL_MATERIAL + 1) === WALL_PALETTES.alt, "ring wall 「界壁」 = material slot 6 (palettes 12 / 13)");
check(WALL_PALETTES.main.join() !== WALL_PALETTES.alt.join() && [WALL_PALETTES.main[3], WALL_PALETTES.alt[3]].every((l) => LAYERS[l].rot === "always"), "wall: alt differs, its patch layers use the rotated second scale (no tiling on flat facets)");
check(new Set(LAYERS.map((l) => l.key)).size === LAYER_COUNT, "unique keys");
for (let i = 0; i < LAYER_COUNT; i++) check(regionsOfLayer(i).length > 0, `layer ${LAYERS[i].key} used by a region`);
for (let p = 0; p < PALETTE_COUNT; p++) {
  const pal = paletteOf(p);
  check(pal.length === 5 && pal.every((l) => l >= 0 && l < LAYER_COUNT), `palette ${p} valid`);
  pal.forEach((l, s) => {
    if (LAYERS[l].rot === "always") check((B_SLOTS as readonly number[]).includes(s), `big-feature ${LAYERS[l].key} only in B slots (palette ${p} slot ${s})`);
  });
  check(pal[0] !== pal[1], `palette ${p}: floor A ≠ floor B`);
}
for (const key of ["basalt", "coralcrust", "lichen"]) check(LAYERS.find((l) => l.key === key)?.rot === "always", `${key} uses the rotated second scale`);
for (let r = 0; r < REGION_COUNT; r++) {
  const { main, alt, altAt } = REGION_PALETTES[r];
  check(main.join() !== alt.join(), `region ${r}: alt differs from main`);
  check(altAt > 0.3 && altAt < 0.8, `region ${r}: alt patches cover part of the region`);
  for (let q = 0; q < r; q++) {
    const a = REGION_PALETTES[q].main;
    const same = main.filter((l, s) => a[s] === l).length;
    check(same <= 3, `regions ${q} and ${r} main palettes distinct (${same}/5 slots equal)`);
    check(new Set(layersOfRegion(r)).size !== new Set(layersOfRegion(q)).size || layersOfRegion(r).some((l) => !layersOfRegion(q).includes(l)), `regions ${q}/${r} layer sets differ`);
  }
}
// ---- layer selection (materialSelect.ts / materialShader.ts SELECT): fixed top-2 per
// surface group, exact with <= 2 distinct layers, continuous everywhere else
{
  let seed = 7;
  const rnd = () => ((seed = (seed * 1103515245 + 12345) >>> 0) / 4294967296);
  const sum = (p: [number, number][]) => p.reduce((a, [, w]) => a + w, 0);
  const asMap = (p: [number, number][]) => {
    const m = new Map<number, number>();
    for (const [l, w] of p) if (w > 0) m.set(l, (m.get(l) ?? 0) + w);
    return m;
  };
  const dist = (a: [number, number][], b: [number, number][]) => {
    const ma = asMap(a), mb = asMap(b);
    let d = 0;
    for (const k of new Set([...ma.keys(), ...mb.keys()])) d = Math.max(d, Math.abs((ma.get(k) ?? 0) - (mb.get(k) ?? 0)));
    return d;
  };
  // exact: duplicates merged, <= 2 distinct layers keep their merged weights
  let exactOk = true, sumOk = true;
  for (let t = 0; t < 2000; t++) {
    const n = 2 + Math.floor(rnd() * 10);
    const c: [number, number][] = Array.from({ length: n }, () => [Math.floor(rnd() * 2) + 5, rnd() < 0.3 ? 0 : rnd()]);
    if (sum(c) === 0) continue;
    if (dist(topTwoJS(c), c) > 1e-9) exactOk = false;
    const d: [number, number][] = Array.from({ length: n }, () => [Math.floor(rnd() * 6), rnd()]);
    if (Math.abs(sum(topTwoJS(d)) - sum(d)) > 1e-9) sumOk = false;
  }
  check(exactOk, "top-2: exact (duplicates merged) with at most two distinct layers");
  check(sumOk, "top-2: group total weight preserved");
  // continuity across a rank-2/3 swap: a layer enters / leaves at weight 0
  {
    let worst = 0;
    for (let k = 0; k <= 2000; k++) {
      const x = k / 2000;
      const a = topTwoJS([[1, 0.5], [2, 0.3], [3, 0.1 + 0.4 * x]]);
      const b = topTwoJS([[1, 0.5], [2, 0.3], [3, 0.1 + 0.4 * (x + 1 / 2000)]]);
      worst = Math.max(worst, dist(a, b));
    }
    check(worst < 0.01, `top-2: no pop when a third layer overtakes (max step ${worst.toFixed(4)})`);
  }
  // the full selection: no jump at the one-palette shortcut borders, at palette rank
  // swaps, or anywhere along random walks of its inputs (away from the degenerate
  // point where the top three weights are equal)
  const slot = () => {
    const f = rnd(), c = rnd() < 0.2 ? rnd() * (1 - f) : 0, fb = rnd(), wb = rnd();
    const w = 1 - f - c;
    return [f * (1 - fb), f * fb, w * (1 - wb), w * wb, c];
  };
  let jump = 0, where = "";
  const eps = 1e-7;
  for (let t = 0; t < 4000; t++) {
    // material slots 0 … 6 (6 = the ring wall)
    const regA = Math.floor(rnd() * (REGION_COUNT + 1));
    let regB = Math.floor(rnd() * (REGION_COUNT + 1));
    if (regB === regA) regB = (regA + 1) % (REGION_COUNT + 1);
    const [a, b] = regA < regB ? [regA, regB] : [regB, regA];
    const sw = slot();
    const edge = [0, 1, rnd()];
    const pm = edge[Math.floor(rnd() * 3)], va = edge[Math.floor(rnd() * 3)], vb = edge[Math.floor(rnd() * 3)];
    const base = selectLayersJS(a, b, pm, va, vb, sw);
    const nudge = (x: number) => (x >= 1 ? x - eps : x + eps);
    for (const [name, r] of [["palMix", selectLayersJS(a, b, nudge(pm), va, vb, sw)], ["vA", selectLayersJS(a, b, pm, nudge(va), vb, sw)], ["vB", selectLayersJS(a, b, pm, va, nudge(vb), sw)]] as const) {
      const d = Math.max(dist(base.floor, r.floor), dist(base.wall, r.wall));
      if (d > jump) {
        jump = d;
        where = `${name} at regions ${a}/${b} palMix ${pm.toFixed(3)} vA ${va.toFixed(3)} vB ${vb.toFixed(3)}`;
      }
    }
  }
  // sweeps of each blend input over [0, 1] (the others at 0, 1 or random): every
  // step is bisected down to 1e-9 of input; a jump that doesn't shrink is a pop.
  // Only the degenerate point (top three weights of one group equal: top-2 of three
  // equal layers has no continuous answer) may keep one; it is counted (pair rescale
  // T / s > 100 there), the rest must shrink to nothing.
  let pops = 0, popAt = "", steps = 0, singular = 0;
  const N = 400;
  for (let t = 0; t < 300; t++) {
    // material slots 0 … 6 (6 = the ring wall)
    const a = Math.floor(rnd() * REGION_COUNT);
    const b = a + 1 + Math.floor(rnd() * (REGION_COUNT - a));
    const sw = slot();
    const edge = [0, 1, rnd()];
    const fixed = [edge[Math.floor(rnd() * 3)], edge[Math.floor(rnd() * 3)], edge[Math.floor(rnd() * 3)]];
    const k = t % 3;
    const at = (x: number, st?: { gain: number }) => {
      const v = [...fixed];
      v[k] = x;
      return selectLayersJS(a, b, v[0], v[1], v[2], sw, st);
    };
    const d = (x: number, y: number) => {
      const p = at(x), q = at(y);
      return Math.max(dist(p.floor, q.floor), dist(p.wall, q.wall));
    };
    for (let i = 0; i < N; i++) {
      steps++;
      let lo = i / N, hi = (i + 1) / N;
      if (d(lo, hi) < 1e-3) continue;
      for (let it = 0; it < 30 && hi - lo > 1e-9; it++) {
        const mid = (lo + hi) / 2;
        if (d(lo, mid) >= d(mid, hi)) hi = mid;
        else lo = mid;
      }
      if (d(lo, hi) < 1e-4) continue;
      const st = { gain: 0 };
      at(lo, st);
      at(hi, st);
      if (st.gain > 100) singular++;
      else {
        pops++;
        popAt = `${["palMix", "vA", "vB"][k]} = ${lo.toFixed(6)}, regions ${a}/${b}, jump ${d(lo, hi).toFixed(4)}`;
      }
    }
  }
  check(pops === 0, `selection has no jumps along input sweeps (${pops}${popAt ? `, e.g. ${popAt}` : ""})`);
  check(singular / steps < 1e-3, `jumps only at the rare top-3-equal point (${singular} of ${steps} steps)`);
  console.log(`  selection: ${steps} sweep steps bisected, 0 pops, ${singular} at the top-3-equal point`);
  check(jump < 1e-3, `selection continuous at the shortcut / rank borders (max jump ${jump.toExponential(2)}${where ? ` ${where}` : ""})`);
}
// terrace keeps the original 4-set look as its main palette
const T = REGION_PALETTES[4].main.map((l) => LAYERS[l].key);
check(T.join() === "sand,gravel,rock,moss,rock", `terrace main = original look (${T})`);

// ---- pipeline / assets
const py = readFileSync("scripts/deep-march-materials.py", "utf8");
const pyKeys = [...py.slice(py.indexOf("SETS = ["), py.indexOf("]", py.indexOf("SETS = ["))).matchAll(/\("(\w+)", "(acg|ph)"/g)].map((m) => m[1]);
check(pyKeys.join() === LAYERS.map((l) => l.key).join(), `pipeline SETS order = catalogue (${pyKeys.join()})`);
const credits = readFileSync("src/games/deep-march/assets/CREDITS.md", "utf8");
const dir = "src/games/deep-march/assets/materials";
const ktx = (f: string) => {
  const b = readFileSync(`${dir}/${f}`);
  const v = new DataView(b.buffer, b.byteOffset, b.byteLength);
  const id = [0xab, 0x4b, 0x54, 0x58, 0x20, 0x32, 0x30, 0xbb, 0x0d, 0x0a, 0x1a, 0x0a];
  check(id.every((x, k) => b[k] === x), `${f}: KTX2 identifier`);
  return { vk: v.getUint32(12, true), w: v.getUint32(20, true), h: v.getUint32(24, true), levels: v.getUint32(40, true), scheme: v.getUint32(44, true) };
};
for (const l of LAYERS) {
  check(credits.includes(`\`${l.key}\``), `CREDITS lists ${l.key}`);
  for (const f of ["a1024.ktx2", "a512.ktx2", "n512.ktx2", "a512.webp", "n512.webp"]) check(existsSync(`${dir}/${l.key}_${f}`), `${l.key}_${f} exists`);
  for (const [f, size, scheme] of [["a1024", 1024, 1], ["a512", 512, 1], ["n512", 512, 2]] as const) {
    if (!existsSync(`${dir}/${l.key}_${f}.ktx2`)) continue;
    const h = ktx(`${l.key}_${f}.ktx2`);
    check(h.vk === 0 && h.w === size && h.h === size, `${l.key}_${f}: ${size}² Basis (vk ${h.vk}, ${h.w}×${h.h})`);
    check(h.levels === Math.log2(size) + 1, `${l.key}_${f}: full mip chain (${h.levels})`);
    check(h.scheme === scheme, `${l.key}_${f}: ${scheme === 1 ? "ETC1S/BasisLZ" : "UASTC+zstd"} (scheme ${h.scheme})`);
  }
}

// ---- generated sizes
{
  const shipped = readdirSync(dir).filter((f) => /\.(ktx2|webp)$/.test(f)).sort();
  check(shipped.join() === Object.keys(MATERIAL_FILE_BYTES).sort().join(), `materialFiles.ts lists exactly the shipped files (${shipped.length})`);
  for (const f of shipped) check(MATERIAL_FILE_BYTES[f] === statSync(`${dir}/${f}`).size, `${f}: size in materialFiles.ts`);
  check(existsSync("src/games/deep-march/scene/materialStream.ts") === false, "no runtime streaming module left");
  const shader = readFileSync("src/games/deep-march/scene/materialShader.ts", "utf8");
  check(!/uLayerS|stand-in|dmFetch/.test(shader.replace(/no stand-ins/, "")), "shader has no stand-in / cross-fade path");
}

// ---- MaterialDownload
{
  const mb = (b: number) => (b / 1e6).toFixed(2);
  for (const low of [false, true]) {
    const d = new MaterialDownload(low);
    const total = pathBytes("ktx2", low);
    let snap = d.snapshot();
    check(snap.done === 0 && snap.total === LAYER_COUNT && snap.bytes === 0 && snap.totalBytes === total && snap.last === -1, `${low ? "phone" : "desktop"}: empty start, total ${mb(total)} MB`);
    check(layerFiles(4, "ktx2", low)[0] === `basalt_a${low ? 512 : 1024}.ktx2` && layerFiles(4, "ktx2", low)[1] === "basalt_n512.ktx2", "ktx2 files per platform");
    // catalogue order, one at a time
    const order: number[] = [];
    for (let k = 0; k < 4; k++) order.push(d.next());
    check(order.join() === "0,1,2,3" && d.state.slice(0, 4).every((s) => s === "loading"), "layers handed out in order, marked loading");
    // byte progress (partial), clamped to the file size
    const [fa, fn] = d.files(0);
    d.progress(fa, 1000);
    d.progress(fn, 1e12);
    snap = d.snapshot();
    check(snap.bytes === 1000 + MATERIAL_FILE_BYTES[fn], `partial bytes counted and clamped (${snap.bytes})`);
    // a failed attempt restarts that file's bytes; retries are bounded
    const retries: boolean[] = [];
    for (let k = 0; k <= MATERIAL_RETRIES; k++) retries.push(d.attemptFailed(fa));
    check(retries.slice(0, MATERIAL_RETRIES).every(Boolean) && !retries[MATERIAL_RETRIES], `${MATERIAL_RETRIES} retries per file, then give up`);
    check(d.snapshot().bytes === MATERIAL_FILE_BYTES[fn], "failed attempt's bytes reset");
    check(d.attemptsOf(fa) === MATERIAL_RETRIES + 1, "attempt count");
    // KTX2 abandoned → every layer again from WebP, totals switch
    d.layerDone(1);
    d.switchToWebp();
    snap = d.snapshot();
    check(snap.path === "webp" && snap.fellBack && snap.done === 0 && snap.bytes === 0 && snap.totalBytes === pathBytes("webp", low) && d.state.every((s) => s === "idle"), "switch to WebP resets everything");
    check(d.files(0)[0] === "sand_a512.webp", "webp files");
    // complete all but one; the last fails for good, user retry brings it back
    let i: number;
    const got: number[] = [];
    while ((i = d.next()) >= 0) got.push(i);
    check(got.length === LAYER_COUNT, "every layer requested (no lazy layers)");
    for (const l of got.slice(0, -1)) {
      for (const f of d.files(l)) d.progress(f, MATERIAL_FILE_BYTES[f]);
      d.layerDone(l);
    }
    const lastL = got[got.length - 1];
    d.layerFailed(lastL);
    snap = d.snapshot();
    check(!d.allDone() && snap.failed === 1 && snap.done === LAYER_COUNT - 1 && snap.last === got[got.length - 2], "final failure blocks completion");
    d.retryFailed();
    check(d.state[lastL] === "idle" && d.next() === lastL, "retry re-requests the failed layer");
    d.layerDone(lastL);
    snap = d.snapshot();
    check(d.allDone() && snap.bytes === snap.totalBytes && snap.done === LAYER_COUNT && snap.failed === 0, "all done: bytes = total");
  }
  console.log(`  download totals: desktop ktx2 ${mb(pathBytes("ktx2", false))} MB · phone ktx2 ${mb(pathBytes("ktx2", true))} MB · webp fallback ${mb(pathBytes("webp", false))} MB`);
}

if (fails) {
  console.error(`${fails} material test(s) failed`);
  process.exit(1);
}
console.log("materials ok");
