#!/usr/bin/env bash
# Rebuild the deep-march WASM noise module (wasm/deep-march/noise.ts, AssemblyScript)
# into src/games/deep-march/terrain/noiseWasmBytes.ts (base64; ~1.7 KB, so it
# compiles synchronously on the main thread and in workers — no asset loading).
# Needs network once for npx; no runtime dependency.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=$(mktemp -d)
npx -y -p assemblyscript@0.28.20 asc wasm/deep-march/noise.ts -O3 --runtime stub --noAssert --memoryBase 0 --initialMemory 1 -o "$OUT/noise.wasm"
B64=$(base64 -w0 "$OUT/noise.wasm")
cat > src/games/deep-march/terrain/noiseWasmBytes.ts <<TS
// Generated by scripts/deep-march-wasm.sh from wasm/deep-march/noise.ts — do not edit.
export const NOISE_WASM_BASE64 = "$B64";
TS
echo "noise.wasm: $(stat -c %s "$OUT/noise.wasm") bytes"
